apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: xdeepseek-maintest-decode
  namespace: aiservice
spec:
  leaderWorkerTemplate:
    leaderTemplate:
      metadata:
        labels:
          role: leader
          pd_role: decode
      spec:
        containers:
        - command:
              - python3
              - -m
              - sglang.launch_server
              - --model-path
              - /work/models
              - --port
              - "30000"
              - --trust-remote
              - --host
              -  0.0.0.0
              - --disaggregation-ib-device
              -  mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
              - --chunked-prefill-size
              - "262144"
              - --eplb-rebalance-layers-per-chunk
              - "29"
              - --page-size
              - "64"
              - --enable-dp-attention
              - --enable-dp-lm-head
              - --dp-size
              - "32"
              - --enable-deepep-moe
              - --deepep-mode
              - low_latency
              - --disaggregation-mode
              - decode
              - --mem-fraction-static
              -  "0.849"
              - --context-length
              - "32768"
              - --cuda-graph-max-bs
              - "64"
              - --max-running-requests
              - "4096"
              - --tp-size
              - "32" # Size of Tensor Parallelism
              - --dist-init-addr
              - $(LWS_LEADER_ADDRESS):20102
              - --nnodes
              - $(LWS_GROUP_SIZE)
              - --node-rank
              - $(LWS_WORKER_INDEX)
              - --trust-remote-code
              - --ep-num-redundant-experts
              - "32"
              - --moe-dense-tp-size
              - "1"
          env:
          - name:  SGLANG_DISAGGREGATION_WAITING_TIMEOUT 
            value: "100000000"
          - name: NVSHMEM_DISABLE_P2P
            value: "0"
          - name: NVSHMEM_IB_TRAFFIC_CLASS
            value: "16"
          - name: NVSHMEM_IB_SL
            value: "5"
          - name: ENABLE_METRICS
            value: "true"
          - name: CUDA_LAUNCH_BLOCKING
            value: "0"
          - name: NVSHMEM_IB_GID_INDEX
            value: "3"

          - name:  NCCL_IB_QPS_PER_CONNECTION
            value: "8"
          - name: NCCL_IB_SPLIT_DATA_ON_QPS
            value: "1"
          - name: NCCL_NET_PLUGIN
            value: "none"
          - name: NCCL_IB_TC
            value: "136"
          - name: NCCL_IB_SL
            value: "5"
          - name: NCCL_IB_TIMEOUT
            value: "22"
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_MIN_NCHANNELS
            value: "4"
          - name: NCCL_SOCKET_IFNAME
            value: bond0
          - name: GLOO_SOCKET_IFNAME
            value: bond0
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: "bond0"
          - name: NCCL_IB_HCA
            value: ^=mlx5_0,mlx5_5,mlx5_6
          - name: MC_TE_METRIC
            value: "false"

          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          - name: MODEL_NAME
          - name: PRETRAINED_MODEL_NAME
            value: deepseek_V3-0324
          - name: FINETUNE_TYPE
            value: full
          - name: TOKENIZER_PATH
            value: /work/models
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          image: sealos.hub:5000/sglang:v0.5.1.post1-cu126-fixip 
          name: sglang-leader
          ports:
          - containerPort: 30000
            protocol: TCP
            name: sglang-http
          name: sglang-leader
          readinessProbe:
            httpGet:
              path: /health
              port: 30000
            periodSeconds: 30           # 每30秒探测一次
            timeoutSeconds: 3           # 每次探测等待响应最多2秒（可调整）
            failureThreshold: 10         # 连续失败5次才判定容器“未就绪”
            successThreshold: 1         # 一次成功即认为就绪
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: 30000 
          #  initialDelaySeconds: 600
          #  periodSeconds: 60           # 每30秒探测一次
          #  timeoutSeconds: 3           # 每次探测等待响应最多2秒（可调整）
          #  failureThreshold: 2         # 连续失败5次才判定容器“未就绪”
          #  successThreshold: 1         # 一次成功即认为就绪
          resources:
            limits:
              nvidia.com/gpu: "8"
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
            privileged: true
          volumeMounts:
          #- name: topo
          #  mountPath: /var/run/sys-topology
          - mountPath: /root/.cache
            name: sgl-cache
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /work/models
            name: model
          - mountPath: /dev/infiniband
            name: ib
          - mountPath: /sgl-workspace/sglang/python/sglang/srt/layers/moe/fused_moe_triton/configs
            name: cf
        dnsPolicy: ClusterFirstWithHostNet
        hostIPC: true
        hostNetwork: true
        nodeSelector: {}
        tolerations:
        - key:  usage
          operator: Equal
          value: "h200-test"
        - key: bopd
          operator: Exists
        - key:  node-role.alibabacloud.com/lingjun
          operator: Exists
        volumes:
        - name: topo
          hostPath:
            path: /var/run/sys-topology

        - hostPath:
            path: /data1/sgl_cache1
            type: DirectoryOrCreate
          name: sgl-cache
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /data/DeepSeek-R1-0528 
          name: model
        - hostPath:
            path: /dev/infiniband
          name: ib
        - hostPath:
            path: /data1/maas_hosted_models/models/fused_moe_triton/configs
          name: cf
    restartPolicy: RecreateGroupOnPodRestart
    size: 4 
    workerTemplate:
      metadata: {}
      spec:
        containers:
        - command:
              - python3
              - -m
              - sglang.launch_server
              - --model-path
              - /work/models
              - --crash-dump-folder
              -  /log
              - --chunked-prefill-size
              - "262144"
              - --eplb-rebalance-layers-per-chunk
              - "29"
              - --page-size
              - "64"
              - --enable-dp-attention
              - --enable-dp-lm-head 
              - --dp-size
              - "32"
              - --enable-deepep-moe
              - --deepep-mode
              - low_latency
              - --disaggregation-mode
              - decode
              - --mem-fraction-static
              -  "0.849"
              - --context-length
              - "32768"
              - --disaggregation-ib-device
              -  mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7 
              - --cuda-graph-max-bs
              - "64"
              - --max-running-requests
              - "4096"
              - --tp-size
              - "32" # Size of Tensor Parallelism
              - --dist-init-addr
              - $(LWS_LEADER_ADDRESS):20102
              - --nnodes
              - $(LWS_GROUP_SIZE)
              - --node-rank
              - $(LWS_WORKER_INDEX)
              - --trust-remote-code
              - --ep-num-redundant-experts
              - "32"
              - --moe-dense-tp-size
              - "1"
          env:
          - name:  SGLANG_DISAGGREGATION_WAITING_TIMEOUT 
            value: "1000000000"
          - name: NVSHMEM_DISABLE_P2P
            value: "0"
          - name: ENABLE_METRICS
            value: "true"
          - name: NVSHMEM_IB_SL
            value: "5"
          - name: CUDA_LAUNCH_BLOCKING
            value: "0"
          - name: SGLANG_HACK_DEEPEP_NUM_SMS
            value: "24"
          - name: SGLANG_HACK_DEEPEP_NEW_MODE
            value: "0"
          - name: NVSHMEM_IB_TRAFFIC_CLASS
            value: "16"
          - name: NVSHMEM_IB_GID_INDEX
            value: "3"
          - name:  NCCL_IB_QPS_PER_CONNECTION
            value: "8"
          - name: NCCL_IB_SPLIT_DATA_ON_QPS
            value: "1"
          - name: NCCL_NET_PLUGIN
            value: "none"
          - name: NCCL_IB_TC
            value: "136"
          - name: NCCL_IB_SL
            value: "5"
          - name: NCCL_IB_TIMEOUT
            value: "22"
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_MIN_NCHANNELS
            value: "4"
          - name: NCCL_SOCKET_IFNAME
            value: bond0
          - name: GLOO_SOCKET_IFNAME
            value: bond0
          - name: NCCL_IB_HCA
            value: ^=mlx5_0,mlx5_5,mlx5_6
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: "bond0"
          - name: MC_TE_METRIC
            value: "true"
          - name: SGLANG_MOONCAKE_TRANS_THREAD
            value: "16"
          - name: SGL_ENABLE_JIT_DEEPGEMM
            value: "1"
          - name: FULL_MODEL_PATH
            value: /work/models/
          - name: TOKENIZER_PATH
            value: /work/models
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          image: sealos.hub:5000/sglang:v0.5.1.post1-cu126-fixip 
          name: sglang-worker
          ports:
          - containerPort: 30001
          resources:
            limits:
              nvidia.com/gpu: "8"
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
            privileged: true
          volumeMounts:
          - mountPath: /root/.cache
            name: sgl-cache
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /work/models
            name: model
          - mountPath: /dev/infiniband
            name: ib
          - mountPath: /sgl-workspace/sglang/python/sglang/srt/layers/moe/fused_moe_triton/configs
            name: cf
        dnsPolicy: ClusterFirstWithHostNet
        hostIPC: true
        hostNetwork: true
        nodeSelector: {}
        tolerations:
        - key:  usage
          operator: Equal
          value: "h200-test"
        - key: bopd
          operator: Exists
        - key:  node-role.alibabacloud.com/lingjun
          operator: Exists
        volumes:
        - name: topo
          hostPath:
            path: /var/run/sys-topology
        - hostPath:
            path: /data1/sgl_cache1
            type: DirectoryOrCreate
          name: sgl-cache
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /dev/infiniband
          name: ib
        - hostPath:
            path: /data/DeepSeek-R1-0528 
          name: model
        - hostPath:
            path: /data1/maas_hosted_models/models/fused_moe_triton/configs
          name: cf
  networkConfig:
    subdomainPolicy: Shared
  replicas: 1
